language: node_js
node_js:
 - 12
install: npm install
script: npm test
notifications:
  email: false
deploy:
  provider: heroku
  app_key:
    secure: "Jo1C1jXm6K8yj4ZyHwcsVkU2YvgM6g+rVx0DFrwQUrRLbLk+evW1/fnOVt72TslFFopFVdxbC37xTjzwWangNjDIgIQxSaQx0t9qUA86ieIAMunkJ+O3gLUv+TrJTPJ3zeFUxDzInJCpR5WHLd4/quhP9QksW2Y6xIHHmS6l00kB62kfOwQYej95Ba7pewYu4DBWr/R4WIhWX/wVCWmvw55FjBKfAchIvnxSmdFKF/7f4QP15rVDdV1ZyLds/5dQU7dM4VUE6iGZ+A7jh+yAeuxBZjWfB7hwrXIl51GTWJ/8Y44WyZxKS8XuuUWCmvSMD9JEocJL7UK25dlcgNnAU3/HRfOfKr01fhHvefQpwku2FHl4+ngbnEoR3mE2jD9AONPPASz20qQsuvtO2Cdp+36o+laPftauxi+LGZDhY04ANFZOuZByaQG3/0MliWJytKcxYk2Hke3ng0HudJ9MopHYVw1+5Hr1C/Cs7EqAxM3BEo0eRpBqPIQEeUacagFEIZUXziWd1QsZKrrZUe/bJDun9Kq3zoBgPWCitn7Zoj/QpeOjQpKqN3PKI5X3pxd79pdViaxCbBRWOBfr2dR+XBNflrG6GiahXs6GUv6S36WBVBuiXdolYJ91fsLh0HsLIrh2000to5SGXMwjmjNjufWbaKhzzdVfNwigx9Sj+iY="
